# Generated by Django 2.1.5 on 2019-01-23 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=100)),
                ('localidade', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=200)),
                ('uf', models.CharField(max_length=100)),
            ],
        ),
    ]
