# Generated by Django 2.1.5 on 2019-01-23 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscacep', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='cep',
            field=models.CharField(default='', max_length=20),
        ),
    ]
